language: go
go_import_path: gg-scm.io/pkg
go: "1.11.x"
install:
  - "if [[ \"$TRAVIS_OS_NAME\" = \"osx\" ]]; then brew install xz; fi"
  - "misc/build-git.bash ~/git \"$GIT_VERSION\""
  - "go get github.com/mattn/goveralls"
  - "go mod download"
script:
  - "PATH=\"$HOME/git/bin-wrappers:$PATH\" go test -v -covermode=count -coverprofile=coverage.out ./..."
  - "goveralls -coverprofile=coverage.out -service=travis-ci"
jobs:
  include:
    # Default
    - os: linux
      env: &stdenv "GIT_VERSION=2.18.0 GO111MODULE=on"
    # Ubuntu Xenial
    - os: linux
      env: GIT_VERSION=2.7.4 GO111MODULE=on
    # Debian Stretch
    - os: linux
      env: GIT_VERSION=2.11.0 GO111MODULE=on
    # macOS
    - os: osx
      env: *stdenv
    - stage: docs
      os: linux
      env: ""
      install: "curl -fsSL https://github.com/gohugoio/hugo/releases/download/v0.42.1/hugo_0.42.1_Linux-64bit.tar.gz | tar zxf - -C \"$HOME\" hugo"
      script:
        - "misc/add-hugo-analytics.bash docs/config.toml UA-2285538-10"
        - "\"$HOME/hugo\" -s docs -d out"
      deploy:
        provider: pages
        fqdn: gg-scm.io
        skip-cleanup: true
        local-dir: docs/out
        github-token: $GITHUB_TOKEN
        keep-history: true
        on:
          branch: master
    - stage: release
      os: linux
      env: ""
      install: go get -u golang.org/x/vgo
      script: &releaseScript "mkdir -p dist && (cd dist && ../misc/release.bash)"
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: dist/*
        skip_cleanup: true
        on:
          tags: true
    - stage: release
      os: osx
      env: ""
      install: go get -u golang.org/x/vgo
      script: *releaseScript
      deploy:
        provider: releases
        api_key: $GITHUB_TOKEN
        file_glob: true
        file: dist/*
        skip_cleanup: true
        on:
          tags: true
stages:
  - test
  - name: doc
    # Include pull requests, but will not run deploy.
    if: branch = master
  - name: release
    if: tag IS present
