baseURL = "https://gg-scm.io/"
languageCode = "en-us"
title = "gg"
disableKinds = ["taxonomy", "taxonomyTerm"]

[permalinks]
commands = "/cmd/:filename/"
workflows = "/workflow/:filename/"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1

[[menu.main]]
identifier = "workflows"
name = "Workflows"
url = "/workflow/"
weight = 2

[[menu.main]]
identifier = "commands"
name = "Commands"
url = "/cmd/"
weight = 3

[[menu.main]]
identifier = "download"
name = "Download"
url = "https://github.com/zombiezen/gg/releases/tag/v0.6.0"
weight = 4

[[menu.main]]
identifier = "github"
name = "GitHub"
url = "https://github.com/zombiezen/gg"
weight = 5

[params]
licenseURL = "https://github.com/zombiezen/gg/blob/master/LICENSE"
latestRelease = "0.6.0"
releaseDate = "2018-07-17"
