# Copyright 2020 The gg Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0

name: Release
on:
  release:
    types: [published]
jobs:
  unix:
    name: Unix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macOS-latest]
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: Check out code
      uses: actions/checkout@v2
    - name: Download dependencies
      run: go mod download
      env:
        GO111MODULE: on
    - name: Package release
      run: release/release.bash
      env:
        GO111MODULE: on
      id: package
    - name: Upload binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./${{ steps.package.outputs.file }}
        asset_name: ${{ steps.package.outputs.file }}
        asset_content_type: application/gzip
  windows:
    name: Windows
    runs-on: windows-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14
    - name: Check out code
      uses: actions/checkout@v2
    - name: Download dependencies
      run: go mod download
      env:
        GO111MODULE: on
    - name: Package release
      run: .\release.ps1 -version ($Env:GITHUB_REF).trimstart('refs/tags/v')
      working-directory: .\release\msi
      id: package
      env:
        GO111MODULE: on
    - name: Upload binary
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: .\release\msi\${{ steps.package.outputs.file }}
        asset_name: ${{ steps.package.outputs.file }}
        asset_content_type: application/gzip
